import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [
    // Document category filter colors - prevent purging
    'bg-blue-100',
    'bg-blue-200',
    'text-blue-700',
    'text-blue-800',
    'hover:bg-blue-200',
    'bg-green-100',
    'bg-green-200',
    'text-green-700',
    'text-green-800',
    'hover:bg-green-200',
    'bg-orange-100',
    'bg-orange-200',
    'text-orange-700',
    'text-orange-800',
    'hover:bg-orange-200',
    'bg-purple-100',
    'bg-purple-200',
    'text-purple-700',
    'text-purple-800',
    'hover:bg-purple-200',
    'bg-pink-100',
    'bg-pink-200',
    'text-pink-700',
    'text-pink-800',
    'hover:bg-pink-200',
    'bg-lime-100',
    'bg-lime-200',
    'text-lime-700',
    'text-lime-800',
    'hover:bg-lime-200',
    'bg-amber-100',
    'bg-amber-200',
    'bg-amber-300',
    'bg-amber-400',
    'text-amber-700',
    'text-amber-800',
    'text-amber-900',
    'hover:bg-amber-200',
    'hover:bg-amber-400',
    'bg-teal-100',
    'bg-teal-200',
    'text-teal-700',
    'text-teal-800',
    'hover:bg-teal-200',
    'bg-indigo-100',
    'bg-indigo-200',
    'text-indigo-700',
    'text-indigo-800',
    'hover:bg-indigo-200',
    'bg-red-100',
    'bg-red-200',
    'text-red-700',
    'text-red-800',
    'hover:bg-red-200',
    'bg-gray-100',
    'bg-gray-200',
    'text-gray-700',
    'text-gray-800',
    'hover:bg-gray-200',
    'bg-violet-100',
    'bg-violet-200',
    'text-violet-700',
    'text-violet-800',
    'hover:bg-violet-200',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('daisyui')],
} satisfies Config;

export default config;
